### ISSUE TITLE
عدم نمایش موجودی ترافیک و تاریخ انقضای کاربران ربات تلگرام

### ISSUE THREAD

**Issue by HaroonxRezaei** [MHSanaei/3x-ui#300]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام چرا موجودی ترافیک و تاریخ انقضای کاربران به صورت ♾Unlimited به کابران نمایش داده میشود؟ آیا امکان حل این مشکل وجود دارد؟

![Untitled](https://user-images.githubusercontent.com/132098661/235233136-c27ee15a-d65e-4f39-b4d5-a988298d9e69.png)

### Version of 3x-ui

<details>

```console
3x-ui: v1.3.3

 Xray: v1.8.1

</details>

### x-ui log reports or xray log

<details>

```console
-- Logs begin at Mon 2023-04-24 23:45:54 UTC, end at Fri 2023-04-28 19:14:06 UTC. --
Apr 28 19:03:02 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: 2023/04/28 19:03:02 WARNING - record not found
Apr 28 19:03:02 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: 2023/04/28 19:03:02 WARNING - Error sending telegram message : Bad Request: message text is empty
Apr 28 19:03:06 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: 2023/04/28 19:03:06 WARNING - Error sending telegram message : Bad Request: message text is empty
Apr 28 19:03:41 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: 2023/04/28 19:03:41 WARNING - Error sending telegram message : Bad Request: message text is empty
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb0f773]
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: goroutine 30 [running]:
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: x-ui/web/service.(*Tgbot).OnReceive(0xc000570000?)
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]:         /home/runner/work/3x-ui/3x-ui/web/service/tgbot.go:98 +0x193
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]: created by x-ui/web/service.(*Tgbot).Start
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e x-ui[3233751]:         /home/runner/work/3x-ui/3x-ui/web/service/tgbot.go:73 +0x4fe
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 28 19:03:59 df3f160f2f664ef8b6e720ceecabb03e systemd[1]: x-ui.service: Failed with result 'exit-code'.
Apr 28 19:04:04 df3f160f2f664ef8b6e720ceecabb03e systemd[1]: x-ui.service: Scheduled restart job, restart counter is at 6.
Apr 28 19:04:04 df3f160f2f664ef8b6e720ceecabb03e systemd[1]: Stopped x-ui Service.
Apr 28 19:04:04 df3f160f2f664ef8b6e720ceecabb03e systemd[1]: Started x-ui Service.
Apr 28 19:04:04 df3f160f2f664ef8b6e720ceecabb03e x-ui[3234847]: 2023/04/28 19:04:04 x-ui 1.3.3
Apr 28 19:04:04 df3f160f2f664ef8b6e720ceecabb03e x-ui[3234847]: 2023/04/28 19:04:04 INFO - web server run http on [::]:2121
Apr 28 19:04:05 df3f160f2f664ef8b6e720ceecabb03e x-ui[3234847]: 2023/04/28 19:04:05 INFO - Tg notify enabled,run at @daily
Apr 28 19:04:05 df3f160f2f664ef8b6e720ceecabb03e x-ui[3234847]: 2023/04/28 19:04:05 INFO - Starting Telegram receiver ...
```

</details>

**Comment by expressV2ray** [comment]
![2023-05-01 08_03_14-s12 happylifee space-Inbounds](https://user-images.githubusercontent.com/132244974/235403903-7cc77d51-fd99-47fe-a504-8873bbaec30d.png)
شما علاوه بر اینکه توی پنل حجم و تاریخ انقضا رو میزنی توی قسمت client هم برای نشون دادن به کاربر باید این مقادیر رو تنظیم کنی

**Comment by HaroonxRezaei** [comment]
خیلی ممنون از پاسخ مفیدتون
